{% set name = "pandera" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86fc52ffde43ed3c16e646f74f12e4c9f39eac029abea9fa16d93d4a47be75b1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .[all] -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pandas
    - pandas-stubs
    - typing_extensions
    - typing_inspect >=0.6.0
    - wrapt
    - packaging
    - pyarrow

    # hypotheses packages
    - scipy

    # io packages
    - pyyaml >=5.1
    - black
    - frictionless
    - click <7.2.0  # frictionless dependency, not a pandera dependency

    # strategies packages
    - hypothesis >=5.41.1

test:
  imports:
    - pandera
    - pandera.hypotheses
    - pandera.io
    - pandera.strategies

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Light-weight and flexible validation for pandas data structures
  description: |
    Pandas data structures hide a lot of information, and explicitly
    validating them in production-critical or reproducible research
    settings is a good idea.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/pandera-dev/pandera

extra:
  recipe-maintainers:
    - cosmicBboy
