{% set name = "pandera" %}
{% set version = "0.10.0" %}

package:
  name: pandera-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7dd66305a9d4b3225de87c4c4845fb92e43085790fafdf9cd0cab835c6fb0eb

build:
  number: 0

outputs:
  - name: pandera-base
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps -vv

    test:
      requires:
        - pip
      imports:
        - pandera
      commands:
        - pip check

    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - numpy >=1.9.0
        - pandas >=1.0
        - pandas-stubs
        - typing_extensions
        - typing_inspect >=0.6.0
        - wrapt
        - packaging >=20.0
        - pyarrow
        - pydantic
    test:
      imports:
        - pandera

  - name: pandera
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}

  - name: pandera-strategies
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.strategies
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - hypothesis >=5.41.1

  - name: pandera-hypotheses
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.hypotheses
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - scipy

  - name: pandera-io
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.io
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyyaml >=5.1
        - black
        - frictionless
        - click <7.2.0  # frictionless dependency, not a pandera dependency

  - name: pandera-pyspark
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.pyspark_accessor
        - pandera.typing.pyspark
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - pyspark

  - name: pandera-modin
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin

  - name: pandera-modin-ray
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-ray

  - name: pandera-modin-dask
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.modin_accessor
        - pandera.typing.modin
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - modin-dask

  - name: pandera-dask
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.dask_accessor
        - pandera.typing.dask
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - dask
        - distributed

  - name: pandera-mypy
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.mypy
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - mypy
        - pandas-stubs

  - name: pandera-fastapi
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.typing.fastapi
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - fastapi

  - name: pandera-geopandas
    build:
      noarch: python
    test:
      requires:
        - pip
      imports:
        - pandera
        - pandera.typing.geopandas
      commands:
        - pip check
    requirements:
      run:
        - {{ pin_subpackage('pandera-base', max_pin="x.x.x") }}
        - geopandas
        - shapely

about:
  home: https://github.com/pandera-dev/pandera
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Light-weight and flexible validation for pandas data structures
  description: |
    A dataframe validation library for scientists, engineers, and analysts
    seeking correctness. Define schemas so you can be confident in the quality
    of your data.
  doc_url: https://pandera.readthedocs.io/en/latest/
  dev_url: https://github.com/pandera-dev/pandera

extra:
  feedstock-name: pandera
  recipe-maintainers:
    - cosmicBboy
